### ISSUE TITLE
Fails with JPEACOCK/version-0.9912_02.tar.gz

### ISSUE THREAD

**Issue by andk** [dagolden/Version-Next#4]
In case you haven't yet noticed...

http://www.cpantesters.org/cpan/report/7f33a0f2-b60d-11e5-916c-aa0a7d43e626

Same with version-0.9912_01

Greetings from Berlin,

**Comment by eserte** [comment]
Fails also with stable 0.9913.

**Comment by eserte** [comment]
The "Lyon Consensus"? → https://gist.github.com/dagolden/9559280

**Comment by xdg** [comment]
Yes, I have to figure out how to deal with this sort of breaking change in version.pm behavior. :-(

**Comment by xdg** [comment]
Support for alpha dotted-decimals has been dropped in Version-Next-1.000
